name: Auto Deploy on Push

on:
  push:
    branches:
      - main  # Adjust this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install SSH key for server access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest code from GitHub on the server and restart services
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@148.113.138.32 << 'EOF'
          cd /var/www/ewsa.cheaptools.club
          echo "Pulling latest changes from GitHub..."
          git pull
          echo "Updating ownership of files..."
          sudo chown -R www-data:www-data /var/www/ewsa.cheaptools.club

        EOF
    - name: Send Telegram notification
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=-4188687896 \
        -d text="🚀 The latest WHITE-GEN code just pulled on the server!"
